services:
  functions:
    build:
      image: registry.crbgroup.cloud/pho-mcp-server:latest
      # dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "${PORT}:3000"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true